// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeOffTracker.Model;

namespace TimeOffTracker.Migrations
{
    [DbContext(typeof(masterContext))]
    [Migration("20210731103101_2021_07_31")]
    partial class _2021_07_31
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeOffTracker.Model.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTimeFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time_from");

                    b.Property<DateTime>("DateTimeTo")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time_to");

                    b.Property<string>("ProjectRoleComment")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("project_role_comment");

                    b.Property<int>("ProjectRoleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("project_role_type_id");

                    b.Property<string>("Reason")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("request_type_id");

                    b.Property<int>("StateDetailId")
                        .HasColumnType("int")
                        .HasColumnName("state_detail_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Request_pk")
                        .IsClustered(false);

                    b.HasIndex(new[] { "ProjectRoleTypeId" }, "IX_Request_project_role_type_id");

                    b.HasIndex(new[] { "RequestTypeId" }, "IX_Request_request_type_id");

                    b.HasIndex(new[] { "StateDetailId" }, "IX_Request_state_detail_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Request_user_id");

                    b.ToTable("Request", "_public");
                });

            modelBuilder.Entity("TimeOffTracker.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("second_name");

                    b.HasKey("Id")
                        .HasName("User_pk")
                        .IsClustered(false);

                    b.HasIndex(new[] { "RoleId" }, "IX_User_role_id");

                    b.HasIndex(new[] { "Email" }, "User_email_uindex")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "User_login_uindex")
                        .IsUnique();

                    b.ToTable("User", "_public");
                });

            modelBuilder.Entity("TimeOffTracker.Model.UserSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved")
                        .HasColumnType("bit")
                        .HasColumnName("approved");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("NInQueue")
                        .HasColumnType("int")
                        .HasColumnName("N_in_queue");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("User_Signature_pk")
                        .IsClustered(false);

                    b.HasIndex(new[] { "RequestId" }, "IX_User_Signature_request_id");

                    b.HasIndex(new[] { "UserId" }, "IX_User_Signature_user_id");

                    b.ToTable("User_Signature", "_public");
                });

            modelBuilder.Entity("TimeOffTracker.Model.Request", b =>
                {
                    b.HasOne("TimeOffTracker.Model.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Request_User_id_fk")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeOffTracker.Model.UserSignature", b =>
                {
                    b.HasOne("TimeOffTracker.Model.Request", "Request")
                        .WithMany("UserSignatures")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("User_Signature_Request_id_fk")
                        .IsRequired();

                    b.HasOne("TimeOffTracker.Model.User", "User")
                        .WithMany("UserSignatures")
                        .HasForeignKey("UserId")
                        .HasConstraintName("User_Signature_User_id_fk")
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeOffTracker.Model.Request", b =>
                {
                    b.Navigation("UserSignatures");
                });

            modelBuilder.Entity("TimeOffTracker.Model.User", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("UserSignatures");
                });
#pragma warning restore 612, 618
        }
    }
}
